<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Makanan;

class MakananSeeder extends Seeder
{
    public function run(): void
    {
        $makananData = [
            // Protein - Daging
            [
                'name' => 'Ayam',
                'kategori' => 'Protein',
                'description' => 'Daging ayam segar, sumber protein tinggi',
                'image' => 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=400&h=400&fit=crop',
                'sumber_data' => 'TKPI 2020',
                'protein' => 25.00,
                'lemak' => 5.00,
                'karbohidrat' => 2.50,
                'kalori' => 165.00,
                'serat' => 0.00,
                'gula' => 0.00,
                'vitamin_a' => 0.05,
                'vitamin_b1' => 0.08,
                'vitamin_b2' => 0.15,
                'vitamin_b3' => 8.50,
                'vitamin_b5' => 1.00,
                'vitamin_b6' => 0.50,
                'vitamin_b12' => 0.30,
                'vitamin_c' => 2.00,
                'natrium' => 70.00,
            ],
            [
                'name' => 'Daging Sapi',
                'kategori' => 'Protein',
                'description' => 'Daging sapi segar, kaya zat besi',
                'image' => 'https://images.unsplash.com/photo-1603048588665-791ca8aea617?w=400&h=400&fit=crop',
                'sumber_data' => 'TKPI 2020',
                'protein' => 26.00,
                'lemak' => 15.00,
                'karbohidrat' => 0.00,
                'kalori' => 250.00,
                'serat' => 0.00,
                'gula' => 0.00,
                'vitamin_a' => 0.00,
                'vitamin_b1' => 0.05,
                'vitamin_b2' => 0.18,
                'vitamin_b3' => 5.00,
                'vitamin_b5' => 0.60,
                'vitamin_b6' => 0.40,
                'vitamin_b12' => 2.00,
                'vitamin_c' => 0.00,
                'natrium' => 60.00,
            ],
            [
                'name' => 'Ikan',
                'kategori' => 'Protein',
                'description' => 'Ikan segar, sumber omega-3',
                'image' => 'https://images.unsplash.com/photo-1574781330855-d0db8cc6a79c?w=400&h=400&fit=crop',
                'sumber_data' => 'TKPI 2020',
                'protein' => 20.00,
                'lemak' => 3.00,
                'karbohidrat' => 0.00,
                'kalori' => 110.00,
                'serat' => 0.00,
                'gula' => 0.00,
                'vitamin_a' => 0.15,
                'vitamin_b1' => 0.10,
                'vitamin_b2' => 0.12,
                'vitamin_b3' => 4.00,
                'vitamin_b5' => 0.80,
                'vitamin_b6' => 0.30,
                'vitamin_b12' => 3.00,
                'vitamin_c' => 1.00,
                'natrium' => 50.00,
            ],

            // Sayuran
            [
                'name' => 'Brokoli',
                'kategori' => 'Sayuran',
                'description' => 'Sayuran hijau kaya vitamin C dan serat',
                'image' => 'https://images.unsplash.com/photo-1628773822503-930a7eaecf80?w=400&h=400&fit=crop',
                'sumber_data' => 'USDA',
                'protein' => 2.80,
                'lemak' => 0.40,
                'karbohidrat' => 7.00,
                'kalori' => 34.00,
                'serat' => 2.60,
                'gula' => 1.70,
                'vitamin_a' => 0.62,
                'vitamin_b1' => 0.07,
                'vitamin_b2' => 0.12,
                'vitamin_b3' => 0.64,
                'vitamin_b5' => 0.57,
                'vitamin_b6' => 0.18,
                'vitamin_b12' => 0.00,
                'vitamin_c' => 89.20,
                'natrium' => 33.00,
            ],
            [
                'name' => 'Wortel',
                'kategori' => 'Sayuran',
                'description' => 'Sayuran orange kaya vitamin A',
                'image' => 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400&h=400&fit=crop',
                'sumber_data' => 'TKPI 2020',
                'protein' => 1.00,
                'lemak' => 0.20,
                'karbohidrat' => 10.00,
                'kalori' => 41.00,
                'serat' => 2.80,
                'gula' => 4.70,
                'vitamin_a' => 16.70,
                'vitamin_b1' => 0.07,
                'vitamin_b2' => 0.06,
                'vitamin_b3' => 1.00,
                'vitamin_b5' => 0.27,
                'vitamin_b6' => 0.14,
                'vitamin_b12' => 0.00,
                'vitamin_c' => 5.90,
                'natrium' => 69.00,
            ],
            [
                'name' => 'Bayam',
                'kategori' => 'Sayuran',
                'description' => 'Sayuran hijau kaya zat besi',
                'image' => 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&h=400&fit=crop',
                'sumber_data' => 'TKPI 2020',
                'protein' => 2.90,
                'lemak' => 0.40,
                'karbohidrat' => 3.60,
                'kalori' => 23.00,
                'serat' => 2.20,
                'gula' => 0.40,
                'vitamin_a' => 9.38,
                'vitamin_b1' => 0.08,
                'vitamin_b2' => 0.19,
                'vitamin_b3' => 0.72,
                'vitamin_b5' => 0.07,
                'vitamin_b6' => 0.20,
                'vitamin_b12' => 0.00,
                'vitamin_c' => 28.10,
                'natrium' => 79.00,
            ],

            // Karbohidrat
            [
                'name' => 'Nasi Putih',
                'kategori' => 'Karbohidrat',
                'description' => 'Nasi putih matang, makanan pokok Indonesia',
                'image' => 'https://images.unsplash.com/photo-1516684732162-798a0062be99?w=400&h=400&fit=crop',
                'sumber_data' => 'TKPI 2020',
                'protein' => 2.70,
                'lemak' => 0.30,
                'karbohidrat' => 28.00,
                'kalori' => 130.00,
                'serat' => 0.40,
                'gula' => 0.05,
                'vitamin_a' => 0.00,
                'vitamin_b1' => 0.02,
                'vitamin_b2' => 0.01,
                'vitamin_b3' => 0.40,
                'vitamin_b5' => 0.39,
                'vitamin_b6' => 0.09,
                'vitamin_b12' => 0.00,
                'vitamin_c' => 0.00,
                'natrium' => 1.00,
            ],
            [
                'name' => 'Kentang',
                'kategori' => 'Karbohidrat',
                'description' => 'Umbi-umbian sumber karbohidrat kompleks',
                'image' => 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400&h=400&fit=crop',
                'sumber_data' => 'USDA',
                'protein' => 2.00,
                'lemak' => 0.10,
                'karbohidrat' => 17.00,
                'kalori' => 77.00,
                'serat' => 2.20,
                'gula' => 0.80,
                'vitamin_a' => 0.00,
                'vitamin_b1' => 0.08,
                'vitamin_b2' => 0.03,
                'vitamin_b3' => 1.05,
                'vitamin_b5' => 0.30,
                'vitamin_b6' => 0.30,
                'vitamin_b12' => 0.00,
                'vitamin_c' => 19.70,
                'natrium' => 6.00,
            ],
        ];

        foreach ($makananData as $data) {
            Makanan::create($data);
        }

        $this->command->info('✓ Berhasil menambahkan ' . count($makananData) . ' data makanan dengan gambar');
    }
}
